project:
  type: book

book:
  title: "aabook"
  author: "Jane Doe"
  date: "10/3/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - model_evaluation.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



